name: Build debian package

on:
  push:
    branches:
      - ros2
    tags:
      - v.*
  pull_request:
    branches:
      - ros2

jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install -y dpkg-dev

      - name: Build debian package
        run: cd debian && ./make_deb.sh
          

#      - name: Upload artifacts
